// Copyright (c) 2026 84EM LLC (https://84em.io). MIT License.
// Generator for the desktop device frame PNG and the frames.json manifest.
// Tablet and mobile frame PNGs come from a third-party open device library
// (see assets/frames/SOURCES.md) and are not regenerated by this script.

import sharp from "sharp";
import { writeFile, mkdir } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(
	dirname(fileURLToPath(import.meta.url)),
	"..",
	"assets",
	"frames",
);

// Desktop monitor: silver bezel, dark inner edge, integrated stand. Drawn as SVG and rasterized.
async function generateDesktop({ outFile }) {
	const W = 1480;
	const H = 1040;
	const screenX = 40;
	const screenY = 40;
	const screenW = 1400;
	const screenH = 800;
	const standTop = screenY + screenH + 20; // 860
	const standNeckW = 220;
	const standBaseW = 460;

	const svg = `
<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}">
  <defs>
    <linearGradient id="bezel" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#cfd1d4"/>
      <stop offset="1" stop-color="#a3a6ab"/>
    </linearGradient>
    <linearGradient id="standGrad" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#b9bcc1"/>
      <stop offset="1" stop-color="#8a8d92"/>
    </linearGradient>
    <mask id="screenCutout">
      <rect width="${W}" height="${H}" fill="white"/>
      <rect x="${screenX}" y="${screenY}" width="${screenW}" height="${screenH}" rx="6" ry="6" fill="black"/>
    </mask>
  </defs>

  <!-- Stand base -->
  <rect x="${(W - standBaseW) / 2}" y="${H - 28}" width="${standBaseW}" height="22" rx="6" ry="6" fill="url(#standGrad)"/>
  <!-- Stand neck -->
  <polygon points="
    ${(W - standNeckW) / 2},${standTop}
    ${(W + standNeckW) / 2},${standTop}
    ${(W + standBaseW) / 2 - 24},${H - 28}
    ${(W - standBaseW) / 2 + 24},${H - 28}
  " fill="url(#standGrad)"/>

  <!-- Monitor body with screen cutout -->
  <rect x="0" y="0" width="${W}" height="${standTop - 8}" rx="22" ry="22" fill="url(#bezel)" mask="url(#screenCutout)"/>

  <!-- Inner dark frame around screen for depth -->
  <rect x="${screenX - 6}" y="${screenY - 6}" width="${screenW + 12}" height="${screenH + 12}" rx="9" ry="9" fill="none" stroke="#1c1c1e" stroke-width="6"/>
</svg>
`;
	const buf = await sharp(Buffer.from(svg)).png().toBuffer();
	await writeFile(outFile, buf);
}

async function main() {
	await mkdir(ROOT, { recursive: true });

	await generateDesktop({ outFile: join(ROOT, "desktop.png") });

	await writeFile(
		join(ROOT, "frames.json"),
		`${JSON.stringify(
			{
				default: {
					desktop: {
						image: "desktop.png",
						canvas: { width: 1480, height: 1040 },
						screen: { x: 40, y: 40, width: 1400, height: 800 },
					},
					tablet: {
						image: "tablet.png",
						canvas: { width: 2068, height: 2788 },
						screen: { x: 200, y: 200, width: 1668, height: 2388 },
					},
					mobile: {
						image: "mobile.png",
						canvas: { width: 1406, height: 2822 },
						screen: { x: 102, y: 100, width: 1206, height: 2622 },
					},
				},
			},
			null,
			2,
		)}\n`,
	);

	console.log("Desktop frame and frames.json written to", ROOT);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
